cuda_visible_devices: "0"
device: gpu

model_name: Extended_NoTemp_w30
logger_name: df_logger_cw.csv
type_graph: max
saving_file: False
binarized: True

data_paths:
  path_logger: HomoGraphs_GovReports/
  results_folder: AttGraphs/GNN_Results_Summarizer/
  root_graph_dataset: datasets/AttnGraphs_GovReports/

load_data_paths:
  in_path: "datasets/GovReport-Sum/"
  data_train: ""
  labels_train: ""
  data_test: ""
  labels_test: ""
  with_val: True

max_len: 200 #1000
