cuda_visible_devices: "0"
device: gpu

#dataset_name: "BBC"
path_models: HomoGraphs_BBC/ #/scratch/mbugueno/HomoGraphs_BBC/
file_to_save: MHAClassifier
logger_name: Extended_Anneal_BBC
logger_file: df_logger_cw_BBC.csv
num_executions: 1 #5
multi_layer: False

load_data_paths:
  in_path: "datasets/BBC/" #"/scratch/datasets/BBC-News/"
  data_train: ""
  labels_train: ""
  data_test: ""
  labels_test: ""
  with_val: True

model_arch_args:
  num_classes: 5
  lr: 0.001
  embed_dim: 384 #sentence transformer
  num_heads: 4
  dropout: 0.2
  hidden_dim : 32 #128
  intermediate: True
  temperature_scheduler : "anneal_decrease"
  temperature_step: 0.0001
  attn_dropout: 0.1  #default 0.0
  activation_attention: "softmax"
  window: 30

batch_size: 32
with_cw: True #or False

trainer_args:
  max_epochs: 5 #20
  enable_progress_bar: False

early_args:
  patience: 1 #5
  min_delta: 0.001