# testing the classifier locally

cuda_visible_devices: "0"
device: gpu

path_models: /HomoGraphs_HND/
file_to_save: MHAClassifier
logger_name: Extended_NoTemp
logger_file: df_logger_cw.csv
num_executions: 2

data_paths:
  in_path: "datasets/HyperNews/"
  data_train: "articles-training-byarticle-20181122.xml"
  labels_train: "ground-truth-training-byarticle-20181122.xml"
  data_test: "articles-test-byarticle-20181207.xml"
  labels_test: "ground-truth-test-byarticle-20181207.xml"
  with_val: False

model_arch_args:
  num_classes: 2
  lr: 0.001
  embed_dim: 384 #sentence transformer
  num_heads: 4
  dropout: 0.2
  hidden_dim : 128
  intermediate: True
  temperature_scheduler : None #="anneal_decrease", temperature_step=0.1
  attn_dropout: 0.1  #default 0.0
  # TODO: pass percentage or None, and list it as arg where needed
  window: 30 # None or percent # min_window_size = 2
  
batch_size: 32
with_cw: True #or False

trainer_args:
  max_epochs: 10
  enable_progress_bar: False

early_args:
  patience: 2
  min_delta: 0.001  